
host = "0.0.0.0"
port = 8080

# INFO:
# Plant order maps to pin order.
# Names must be unique.

[[plants]]
amountMl = 500
name = "Karsten"
# My spathiphyllum wallisii, which often has hanging leafs.
# Named after a german TV legend.
# "Was ist denn mit Karsten los?"

[[plants]]
amountMl = 500
name = "Bazil"
# My bazil.
# Named after Picture of Dorian Grey character Bazil.

